import 'package:flutter/material.dart';

List<String> list = [
  "Null",
  "Hubbali Railway Station",
  "Hubbali CBT",
  "Dr B R Ambedkar Circle",
  "HDMC",
  "Hubbali Central Bus Stand",
  "Hosur cross",
  "Hosur Regional Bus Station",
  "KIMS",
  "Vidya Nagar",
  "BVB",
  "Unkal Lake",
  "Bairidevarkoppa",
  "Shantiniketan",
  "APMC 3rd Gate",
  "Navanagar",
  "RTO",
  "ISKON",
  "Rayapur",
  "KMF1",
  "Navalur Railway Station",
  "SDM Med College",
  "SATTUR",
  "Lakamanahalli",
  "Gandhi Nagar",
  "Vidyagiri",
  "Tollnaka",
  "Hosayellapur",
  "NTTF",
  "Dharwad Court Circle",
  "Jubilee Circle",
  "Dharwad New Bus Stand"
];
